import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyAction} from '../lib/domain.mjs';
import {resolveAccess,visibleState,assertPermission} from '../lib/access.mjs';
const now=new Date('2026-10-05T12:30:00+03:00');
const owner={id:'u1',name:'مالك اختبار',email:'OWNER@example.test',phone:'',role:'owner',status:'active',salonName:'صالون الاختبار',customerId:''};
const customer={id:'u2',name:'عميل اختبار',email:'client@example.test',phone:'',role:'customer',status:'active',salonName:'',customerId:'c1'};
const save=(s,data)=>applyAction(s,{type:'saveUser',data},now);
const setup=()=>save(save(initialState(),owner),customer);
const identity=email=>({userId:'other-user',email,displayName:'اختبار'});
test('legacy state gets users lazily without losing bookings',()=>{const s=setup();assert.equal(s.users.length,2);assert.equal(s.bookings.length,4)});
test('email normalized and unique case insensitive',()=>{const s=setup();assert.equal(s.users[0].email,'owner@example.test');assert.throws(()=>save(s,{...owner,id:'duplicate'}),/البريد/)});
test('customer requires a valid linked profile',()=>assert.throws(()=>save(initialState(),{...customer,customerId:'missing'})));
test('customer profile cannot link to two accounts',()=>assert.throws(()=>save(setup(),{...customer,id:'another',email:'another@example.test'})));
test('cannot forge admin role',()=>assert.throws(()=>save(initialState(),{...owner,role:'admin'})));
test('actual owner remains admin regardless of members',()=>assert.equal(resolveAccess(setup(),{userId:'root',email:'root@example.test'},'root').role,'admin'));
test('no membership grants no shared access',()=>assert.throws(()=>resolveAccess(setup(),identity('unknown@example.test'),'root')));
test('active owner can operate but not administer accounts',()=>{const a=resolveAccess(setup(),identity('owner@example.test'),'root');assert.equal(a.role,'owner');assert.doesNotThrow(()=>assertPermission(a,{type:'saveBooking'}));for(const type of ['saveUser','userStatus','clearDemo'])assert.throws(()=>assertPermission(a,{type}))});
test('client cannot mutate any workspace action',()=>{const a=resolveAccess(setup(),identity('client@example.test'),'root');for(const type of ['saveBooking','settings','status','saveUser'])assert.throws(()=>assertPermission(a,{type}))});
test('client projection removes other customers, internal notes and accounts',()=>{const s=setup();s.customers[0].notes='private';s.bookings[0].notes='internal';const a=resolveAccess(s,identity('client@example.test'),'root');const v=visibleState(s,a);assert.equal(v.customers.length,1);assert.ok(v.bookings.every(b=>b.customerId==='c1'));assert.equal(v.customers[0].notes,'');assert.equal(v.bookings[0].notes,'');assert.deepEqual(v.users,[]);assert.deepEqual(v.audit,[]);assert.equal(s.bookings[0].notes,'internal')});
test('suspension enforced at next access and reactivation restores it',()=>{let s=applyAction(setup(),{type:'userStatus',id:'u1',status:'suspended'},now);assert.throws(()=>resolveAccess(s,identity('owner@example.test'),'root'));s=applyAction(s,{type:'userStatus',id:'u1',status:'active'},now);assert.equal(resolveAccess(s,identity('owner@example.test'),'root').role,'owner')});
test('linked user prevents deleting customer and demo reset',()=>{let s=setup();assert.throws(()=>applyAction(s,{type:'deleteCustomer',id:'c1'},now));assert.throws(()=>applyAction(s,{type:'clearDemo'},now))});
test('role updates revoke customer scope and preserve creation date',()=>{const s=save(setup(),{...customer,role:'owner',salonName:'صالون جديد'});assert.equal(s.users[1].customerId,'');assert.equal(s.users[1].createdAt,now.toISOString())});
