import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyAction,stats,dayNow} from '../lib/domain.mjs';
const now=new Date('2026-10-05T12:30:00+03:00');
const initial=()=>initialState('2026-10-05');
const book=(s,over={})=>applyAction(s,{type:'saveBooking',data:{id:'new',customerId:'c4',staffId:'e1',serviceId:'s1',date:'2026-10-05',time:'11:00',notes:'',...over}},now);
test('adjacent booking allowed, original unchanged',()=>{const s=initial();assert.equal(book(s).bookings.length,5);assert.equal(s.bookings.length,4)});
test('staff buffer overlap rejected',()=>assert.throws(()=>book(initial(),{time:'10:50'}),/تعارض/));
test('customer overlap across staff rejected',()=>assert.throws(()=>book(initial(),{customerId:'c2',staffId:'e1',time:'11:15'}),/متداخل/));
test('outside hours including buffer rejected',()=>assert.throws(()=>book(initial(),{time:'20:30'}),/ساعات/));
test('cancelled slot reusable',()=>{const s=applyAction(initial(),{type:'status',id:'b2',status:'cancelled'},now);assert.equal(book(s,{staffId:'e2'}).bookings.length,5)});
test('invalid calendar date rejected',()=>assert.throws(()=>book(initial(),{date:'2026-02-30'})));
test('past date rejected',()=>assert.throws(()=>book(initial(),{date:'2026-10-04'}),/سابق/));
test('unknown customer rejected',()=>assert.throws(()=>book(initial(),{customerId:'missing'})));
test('invalid status transition rejected',()=>assert.throws(()=>applyAction(initial(),{type:'status',id:'b2',status:'completed'},now),/غير مسموح/));
test('early no-show rejected',()=>assert.throws(()=>applyAction(initial(),{type:'status',id:'b4',status:'noshow'},now),/لم يحن/));
test('normalized phone duplicate rejected',()=>{let s=applyAction(initial(),{type:'saveCustomer',data:{id:'new1',name:'اختبار',phone:'0501234567'}},now);assert.throws(()=>applyAction(s,{type:'saveCustomer',data:{id:'new2',name:'اختبار',phone:'+966501234567'}},now),/مسجل/)});
test('linked customer deletion rejected',()=>assert.throws(()=>applyAction(initial(),{type:'deleteCustomer',id:'c1'},now),/مرتبطة/));
test('staff with bookings cannot deactivate',()=>assert.throws(()=>applyAction(initial(),{type:'saveStaff',data:{...initial().staff[0],active:false}},now)));
test('settings cannot invalidate open bookings',()=>assert.throws(()=>applyAction(initial(),{type:'settings',data:{name:'اختبار',open:'09:00',close:'14:00'}},now)));
test('booked price snapshot survives service price update',()=>{let s=book(initial());s=applyAction(s,{type:'saveService',data:{...s.services[0],price:80000}},now);s=book(s,{time:'12:00'});assert.equal(s.bookings.find(b=>b.id==='new').price,15000)});
test('complete journey and stats',()=>{let s=initial();for(const status of ['arrived','inservice','completed'])s=applyAction(s,{type:'status',id:'b2',status},now);assert.equal(stats(s.bookings).value,37000);assert.equal(stats(s.bookings).completed,2)});
test('empty stats use null delay',()=>assert.equal(stats([]).delay,null));
test('Riyadh date crosses UTC midnight correctly',()=>assert.equal(dayNow(new Date('2026-10-05T22:00:00Z')),'2026-10-06'));
test('clearing demo cannot repeat',()=>{const s=applyAction(initial(),{type:'clearDemo'},now);assert.equal(s.bookings.length,0);assert.throws(()=>applyAction(s,{type:'clearDemo'},now))});
