"use client";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Picker,Badge,BookingTable,money,formatAt} from './ui';
export default function Forms(p:any){const {data,modal,setModal,form,setForm,formError,setFormError,confirm,setConfirm,busy,act,open}=p;const kind=modal?.kind;const change=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));const input=(key:string,label:string,type='text',extra:any={})=><label className="field"><span>{label}</span><input required type={type} value={form[key]??''} onInput={e=>change(key,e.currentTarget.value)} {...extra}/></label>;const active=<label className="switch-row"><span>متاحة للحجوزات الجديدة</span><Switch checked={form.active} onCheckedChange={v=>change('active',v)}/></label>;const b=data.bookings.find((x:any)=>x.id===modal?.item?.id);const title:any={booking:'تفاصيل الحجز',customer:'بيانات العميلة',service:'بيانات الخدمة',staff:'بيانات الموظفة',settings:'إعدادات الفرع',detail:'متابعة الموعد',customerHistory:'سجل الزيارات'};
async function submit(e:any){e.preventDefault();setFormError('');const types:any={booking:'saveBooking',customer:'saveCustomer',staff:'saveStaff',service:'saveService',settings:'settings'};const value=kind==='service'?{...form,duration:Number(form.duration),buffer:Number(form.buffer),price:Math.round(Number(form.price))}:form;if(await act({type:types[kind],data:value}))setModal(null)}
return <><Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal(null)}}><DialogContent dir="rtl" className="product-dialog"><DialogHeader><DialogTitle>{title[kind]||'التفاصيل'}</DialogTitle><DialogDescription>{kind==='booking'?'يُفحص تداخل المواعيد ووقت الخدمة والفاصل قبل الحفظ.':'التوقيت المعتمد: المملكة العربية السعودية.'}</DialogDescription></DialogHeader>{formError&&<div role="alert" className="error">{formError}</div>}
{kind==='detail'&&b?<div className="detail"><Badge status={b.status}/><h2>{data.customers.find((x:any)=>x.id===b.customerId)?.name}</h2><p>{b.serviceName} · {money(b.price)}</p><p>{b.date} · <b dir="ltr">{b.time}</b> · {data.staff.find((x:any)=>x.id===b.staffId)?.name}</p><p>{b.duration} دقيقة للخدمة + {b.buffer} دقيقة فاصل</p><p>بدء الخدمة: {formatAt(b.started)} · الانتهاء: {formatAt(b.finished)}</p>{b.notes&&<p className="note">{b.notes}</p>}<div className="actions">{({booked:[['arrived','تسجيل الوصول']],arrived:[['inservice','بدء الخدمة']],inservice:[['completed','إنهاء الخدمة']]} as any)[b.status]?.map(([status,label]:string[])=><button key={status} disabled={busy} className="primary" onClick={async()=>{if(await act({type:'status',id:b.id,status}))setModal(null)}}>{label}</button>)}{b.status==='booked'&&<><button onClick={()=>open('booking',b)}>تعديل الحجز</button><button disabled={busy} onClick={()=>setConfirm({title:'تسجيل عدم الحضور؟',description:'يمكن تسجيل ذلك بعد وقت الموعد في اليوم نفسه.',action:{type:'status',id:b.id,status:'noshow'}})}>لم تحضر</button></>}{['booked','arrived'].includes(b.status)&&<button className="danger" disabled={busy} onClick={()=>setConfirm({title:'إلغاء هذا الموعد؟',description:'سيبقى الموعد في السجل، ويصبح الوقت متاحًا لحجز آخر.',action:{type:'status',id:b.id,status:'cancelled'}})}>إلغاء الموعد</button>}</div></div>:kind==='customerHistory'?<BookingTable rows={data.bookings.filter((x:any)=>x.customerId===modal.item.id)} data={data} open={open}/>:kind!=='detail'&&<form onSubmit={submit} className="edit-form"><fieldset disabled={busy}>
{kind==='booking'&&<><Picker label="العميلة" value={form.customerId} options={data.customers} onChange={v=>change('customerId',v)}/><Picker label="الخدمة" value={form.serviceId} options={data.services.filter((s:any)=>s.active||s.id===form.serviceId)} onChange={v=>change('serviceId',v)}/><Picker label="الموظفة" value={form.staffId} options={data.staff.filter((s:any)=>s.active)} onChange={v=>change('staffId',v)}/><div className="form-grid">{input('date','التاريخ','date')}{input('time','الوقت','time')}</div>{(!data.customers.length||!data.staff.length||!data.services.length)&&<p className="note">أضيفي عميلة وموظفة وخدمة أولًا من القوائم الرئيسية.</p>}</>}
{kind==='customer'&&<>{input('name','اسم العميلة','text',{maxLength:80,minLength:2})}{input('phone','رقم الجوال (اختياري)','tel',{required:false,placeholder:'05xxxxxxxx',maxLength:16})}</>}
{kind==='staff'&&<>{input('name','اسم الموظفة','text',{minLength:2,maxLength:80})}{input('role','التخصص','text',{required:false,maxLength:80})}<div className="form-grid">{input('start','بداية الدوام','time')}{input('end','نهاية الدوام','time')}</div>{active}</>}
{kind==='service'&&<>{input('name','اسم الخدمة','text',{minLength:2,maxLength:80})}<div className="form-grid">{input('duration','مدة الخدمة بالدقائق','number',{min:5,max:480})}{input('buffer','الفاصل بعد الخدمة','number',{min:0,max:120})}</div><label className="field"><span>السعر بالريال</span><input required type="number" min="0" max="100000" step="0.01" value={form.price/100} onInput={e=>change('price',Math.round(Number(e.currentTarget.value)*100))}/></label>{active}</>}
{kind==='settings'&&<>{input('name','اسم الصالون','text',{minLength:2,maxLength:80})}<div className="form-grid">{input('open','بداية العمل','time')}{input('close','نهاية العمل','time')}</div></>}
{['booking','customer'].includes(kind)&&<label className="field"><span>ملاحظات (اختياري)</span><textarea maxLength={500} value={form.notes} onInput={e=>change('notes',e.currentTarget.value)}/></label>}<div className="actions"><button className="primary" type="submit">{busy?'جارٍ الحفظ…':'حفظ التغييرات'}</button><button type="button" onClick={()=>setModal(null)}>رجوع</button></div></fieldset></form>}</DialogContent></Dialog>
<AlertDialog open={!!confirm} onOpenChange={v=>{if(!v&&!busy)setConfirm(null)}}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>رجوع</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(await act(confirm.action)){setConfirm(null);setModal(null)}}}>{busy?'جارٍ التنفيذ…':'تأكيد'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>}



