"use client";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Table,TableHeader,TableRow,TableHead,TableBody,TableCell } from '@/components/ui/table';
import { statusLabels } from '@/lib/domain.mjs';
import type {State,Booking} from './types';
export const labels:Record<string,string>=statusLabels;
export const money=(n:number)=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2}).format(n/100)+' ر.س';
export const num=(n:number)=>new Intl.NumberFormat('ar-SA').format(n);
export const humanDate=(d:string)=>new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{weekday:'long',day:'numeric',month:'long'}).format(new Date(d+'T12:00:00+03:00'));
export const formatAt=(s?:string)=>s?new Intl.DateTimeFormat('ar-SA',{timeZone:'Asia/Riyadh',hour:'2-digit',minute:'2-digit'}).format(new Date(s)):'—';
export function Picker({label,value,options,onChange}:{label:string;value:string;options:{id:string;name:string}[];onChange:(s:string)=>void}){return <label className="field"><span>{label}</span><Select dir="rtl" value={value||undefined} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue placeholder="اختاري…"/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></label>}
export function Badge({status}:{status:string}){return <span className={'badge status-'+status}>{labels[status]}</span>}
export function Metrics({items}:{items:string[][]}){return <div className="metrics">{items.map(([a,b,c])=><section className="metric" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></section>)}</div>}
export function BookingTable({rows,data,open}:{rows:Booking[];data:State;open:(k:string,x:any)=>void}){return <><Table><TableHeader><TableRow>{['الموعد','العميلة','الخدمة','الموظفة','الحالة','القيمة',''].map((s,i)=><TableHead key={i}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(b=><TableRow key={b.id}><TableCell><strong dir="ltr">{b.time}</strong><small className="block">{b.date}</small></TableCell><TableCell>{data.customers.find(c=>c.id===b.customerId)?.name}</TableCell><TableCell>{b.serviceName}<small className="block">{b.duration} دقيقة + {b.buffer} فاصل</small></TableCell><TableCell>{data.staff.find(s=>s.id===b.staffId)?.name}</TableCell><TableCell><Badge status={b.status}/></TableCell><TableCell>{money(b.price)}</TableCell><TableCell><button className="text-button" onClick={()=>open('detail',b)}>التفاصيل</button></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<div className="empty">لا توجد حجوزات مطابقة.</div>}</>}
export function exportCsv(rows:Booking[],data:State){const cell=(x:any)=>{let s=String(x??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const lines=[['التاريخ','الوقت','العميلة','الموظفة','الخدمة','الحالة','قيمة الخدمة ر.س','بدء فعلي','انتهاء فعلي'],...rows.map(b=>[b.date,b.time,data.customers.find(c=>c.id===b.customerId)?.name,data.staff.find(s=>s.id===b.staffId)?.name,b.serviceName,labels[b.status],b.price/100,b.started||'',b.finished||''])];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='mawaeed-bookings.csv';a.click();URL.revokeObjectURL(url)}
