"use client";
import {useState} from 'react';
import {Search,UserRound,Building2,UsersRound,ShieldCheck,PauseCircle,CheckCircle2,Pencil,Link2,ArrowUpLeft} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import type {State,Access,Member} from './types';
import {Picker,num} from './ui';
export default function UserCenter({data,access,open,setConfirm,busy}:{data:State;access:Access;open:(k:string,item?:any,defaults?:any)=>void;setConfirm:(x:any)=>void;busy:boolean}){
 const [role,setRole]=useState('all'),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[invite,setInvite]=useState<Member|null>(null);
 const users=data.users||[];
 const rows=users.filter(u=>(role==='all'||u.role===role)&&(status==='all'||u.status===status)&&[u.name,u.email,u.phone,u.salonName].join(' ').toLowerCase().includes(query.toLowerCase().trim()));
 const link=typeof window==='undefined'?'':window.location.origin+'/dashboard?workspace='+encodeURIComponent(access.workspaceId);
 return <><div className="center-summary">{[{label:'المستخدمون المسجلون',value:users.length,Icon:UsersRound},{label:'ملاك الصالونات',value:users.filter(u=>u.role==='owner').length,Icon:Building2},{label:'العملاء',value:users.filter(u=>u.role==='customer').length,Icon:UserRound},{label:'وصول نشط',value:users.filter(u=>u.status==='active').length,Icon:CheckCircle2}].map(({label,value,Icon})=><section key={label}><span className="summary-icon"><Icon size={18}/></span><div><span>{label}</span><strong>{num(value)}</strong></div></section>)}</div>
 <div className="admin-strip"><div className="admin-identity"><ShieldCheck size={23}/><div><strong>{access.name}</strong><span dir="ltr">{access.email}</span></div></div><span className="role-chip admin">مسؤول المساحة</span><p>إدارة المستخدمين والصلاحيات متاحة لهذا الحساب.</p></div>
 <section className="panel user-panel"><div className="panel-title"><Tabs value={role} onValueChange={setRole} dir="rtl"><TabsList><TabsTrigger value="all">الجميع</TabsTrigger><TabsTrigger value="owner">ملاك الصالونات</TabsTrigger><TabsTrigger value="customer">العملاء</TabsTrigger></TabsList></Tabs><span>{num(rows.length)} مستخدم</span></div><div className="user-filters"><label className="search"><Search size={16}/><input aria-label="بحث المستخدمين" placeholder="ابحث بالاسم، البريد أو الصالون…" value={query} onInput={e=>setQuery(e.currentTarget.value)}/></label><Picker label="حالة الوصول" value={status} onChange={setStatus} options={[{id:'all',name:'جميع الحالات'},{id:'active',name:'نشط'},{id:'suspended',name:'معلق'}]}/></div>
 <Table><TableHeader><TableRow>{['المستخدم','الدور','الارتباط','الحالة','تاريخ الإضافة','الإجراءات'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(u=><TableRow key={u.id}><TableCell><div className="person"><span className={'avatar '+(u.role==='owner'?'color0':'color1')}>{u.name[0]}</span><div><strong>{u.name}</strong><small className="block" dir="ltr">{u.email}</small></div></div></TableCell><TableCell><span className={'role-chip '+u.role}>{u.role==='owner'?<Building2 size={13}/>:<UserRound size={13}/>}{u.role==='owner'?'مالك صالون':'عميل'}</span></TableCell><TableCell>{u.role==='owner'?u.salonName:data.customers.find(c=>c.id===u.customerId)?.name||'غير مرتبط'}</TableCell><TableCell><span className={'account-status '+u.status}><i/>{u.status==='active'?'نشط':'معلق'}</span></TableCell><TableCell>{new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{dateStyle:'medium',timeZone:'Asia/Riyadh'}).format(new Date(u.createdAt))}</TableCell><TableCell><div className="row-actions"><button className="icon-button" aria-label={'تعديل المستخدم '+u.name} disabled={busy} onClick={()=>open('user',u)}><Pencil size={15}/></button><button className="icon-button" aria-label={'رابط دخول '+u.name} onClick={()=>setInvite(u)}><Link2 size={16}/></button><button className="icon-button" aria-label={(u.status==='active'?'تعليق ':'تفعيل ')+u.name} disabled={busy} onClick={()=>setConfirm({title:u.status==='active'?'تعليق وصول المستخدم؟':'تفعيل وصول المستخدم؟',description:u.status==='active'?'سيُرفض وصول هذا الحساب إلى المساحة في الطلب التالي. تبقى بياناته وحجوزاته محفوظة.':'سيتمكن هذا الحساب من الوصول بحسب الدور المحدد له.',action:{type:'userStatus',id:u.id,status:u.status==='active'?'suspended':'active'}})}>{u.status==='active'?<PauseCircle size={17}/>:<CheckCircle2 size={17}/>}</button></div></TableCell></TableRow>)}</TableBody></Table>
 {!rows.length&&<div className="empty user-empty"><UsersRound size={32}/><h3>{users.length?'لا توجد نتائج مطابقة':'ابدأ بإضافة أول مستخدم'}</h3><p>{users.length?'جرّب اسمًا آخر أو غيّر عوامل التصفية.':'أضف مالك صالون لإدارة التشغيل، أو اربط عميلًا بحجوزاته.'}</p>{!users.length&&<button className="text-button" onClick={()=>open('user')}>إضافة مستخدم <ArrowUpLeft size={15}/></button>}</div>}</section>
 <div className="permission-cards"><section><Building2 size={20}/><h3>مالك الصالون</h3><p>يدير حجوزات هذه المساحة والعملاء والفريق والتقارير. لا يمكنه إدارة المستخدمين أو صلاحياتهم.</p></section><section><UserRound size={20}/><h3>حساب العميل</h3><p>يعرض حجوزات ملف العميل المرتبط به فقط، دون بيانات الآخرين أو الملاحظات الداخلية.</p></section><section><ShieldCheck size={20}/><h3>الدخول والصلاحيات</h3><p>الدخول بالحساب ذي البريد المسجل. الرابط لا يمنح صلاحية وحده، ولا تُرسل دعوات تلقائية.</p></section></div>
 <p className="note">الشركاء المضافون هنا يعملون داخل هذا الفرع فقط. أنشئ الفروع المستقلة من بوابة الشركاء، وأضف مستخدمي كل فرع داخل لوحته. الوصول الخارجي يتطلب إتاحة الموقع للحساب المعني أيضًا؛ الموقع الخاص بالمؤسس لا يفتح تلقائيًا للمستخدمين المضافين.</p>
 <Dialog open={!!invite} onOpenChange={v=>!v&&setInvite(null)}><DialogContent dir="rtl"><DialogHeader><DialogTitle>رابط دخول {invite?.name}</DialogTitle><DialogDescription>يجب تسجيل الدخول بالبريد {invite?.email} وإتاحة الموقع لهذا الحساب. لا تُنشأ كلمة مرور جديدة.</DialogDescription></DialogHeader><input className="invite-link" aria-label="رابط المساحة" value={link} readOnly dir="ltr"/><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(link);toast.success('تم نسخ الرابط')}catch{toast.error('تعذر النسخ التلقائي؛ انسخ الرابط من الحقل')}}}>نسخ الرابط</button><p className="note">{invite?.status==='suspended'?'هذا الحساب معلق ولن يتمكن من الوصول حتى تفعيله.':'لم يتم إرسال رسالة؛ يمكنك مشاركة الرابط بعد تجهيز صلاحية الموقع.'}</p></DialogContent></Dialog></>;
}

