"use client";
import {useState,useEffect,useRef} from 'react';
import { CalendarDays, Clock3, Users, Scissors, ChartNoAxesCombined, Plus, Settings2, RefreshCw, Sparkles } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarFooter, SidebarInset, SidebarTrigger } from '@/components/ui/sidebar';
import { Toaster } from '@/components/ui/sonner';
import {toast} from 'sonner';
import {dayNow} from '@/lib/domain.mjs';
import type {State} from './types';
import {humanDate} from './ui';
import Views from './views';
import Forms from './forms';
const names:Record<string,string>={today:'نظرة اليوم',bookings:'الحجوزات',customers:'العميلات',team:'الخدمات والفريق',reports:'التقارير',settings:'الإعدادات'};
export default function Workspace(){
 const [data,setData]=useState<State|null>(null),[rev,setRev]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState('today'),[date,setDate]=useState(dayNow()),[teamTab,setTeamTab]=useState('services');
 const [modal,setModal]=useState<{kind:string;item?:any}|null>(null),[form,setForm]=useState<any>({}),[formError,setFormError]=useState(''),[confirm,setConfirm]=useState<any>(null);
 const busyRef=useRef(false),live=useRef({data,rev,date});live.current={data,rev,date};
 async function load(){setLoading(true);try{const r=await fetch('/api/workspace',{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j.state);setRev(j.revision);setError('')}catch(e:any){setError(e.message||'تعذر الاتصال')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function act(action:any){if(busyRef.current)return false;busyRef.current=true;setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:live.current.rev,action})});const j:any=await r.json();if(!r.ok){if(r.status===409)await load();throw Error(j.error||'تعذر الحفظ')}setData(j.state);setRev(j.revision);live.current={...live.current,data:j.state,rev:j.revision};setError('');toast.success('تم الحفظ');return true}catch(e:any){setFormError(e.message);toast.error(e.message);return false}finally{busyRef.current=false;setBusy(false)}}
 function open(kind:string,item?:any,defaults?:any){setFormError('');setModal({kind,item});setForm(item?{...item}:{id:crypto.randomUUID(),name:'',phone:'',notes:'',role:'',start:'09:00',end:'21:00',active:true,duration:45,buffer:10,price:0,customerId:'',staffId:'',serviceId:'',date:live.current.date,time:'10:00',...defaults})}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[{name:'read_salon_day',description:'Read bookings for a Saudi calendar date. Does not change records.',inputSchema:{type:'object',properties:{date:{type:'string',pattern:'^20[0-9]{2}-[0-9]{2}-[0-9]{2}$'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!/^20\d{2}-\d{2}-\d{2}$/.test(input?.date))throw Error('Invalid date');if(!live.current.data)throw Error('Workspace not loaded');return live.current.data.bookings.filter(b=>b.date===input.date).map(b=>({id:b.id,time:b.time,status:b.status,service:b.serviceName}))}},{name:'start_salon_booking',description:'Open the booking form; does not create or save a booking.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{if(!live.current.data)throw Error('Workspace not loaded');open('booking');return {opened:true,saved:false}}}];for(const t of tools)try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
 return <SidebarProvider><Toaster position="top-center" richColors dir="rtl"/><Sidebar side="right"><SidebarHeader><div className="brand"><span>م</span><strong>مواعيد<small>مساحة إدارة الصالون</small></strong></div></SidebarHeader><SidebarContent><SidebarMenu>{[[CalendarDays,'today'],[Clock3,'bookings'],[Users,'customers'],[Scissors,'team'],[ChartNoAxesCombined,'reports'],[Settings2,'settings']].map(([Icon,key])=>{const I=Icon as typeof CalendarDays;return <SidebarMenuItem key={String(key)}><SidebarMenuButton isActive={page===key} size="lg" onClick={()=>setPage(String(key))}><I/><span>{names[String(key)]}</span></SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu><div className="sidebar-note"><Sparkles size={21}/><strong>مساحة ليوم أكثر هدوءًا</strong><p>جدول واضح، فريق متوازن، ووقت أفضل لكل عميلة.</p></div></SidebarContent><SidebarFooter><div className="branch">{data?.settings.name||'صالوني'}<small>فرع واحد · توقيت السعودية</small></div></SidebarFooter></Sidebar><SidebarInset><header className="topbar"><div><SidebarTrigger/><span>{names[page]}</span></div><div><button className="icon-button" aria-label="تحديث البيانات" disabled={loading||busy} onClick={()=>load()}><RefreshCw size={17}/></button><span className="demo">{data?.demo?'بيانات تجريبية':'مساحة خاصة'}</span><span className="avatar color0">م</span></div></header><main className="workspace">
 {error&&<div role="alert" className="error">{error}<button onClick={()=>load()}>إعادة المحاولة</button></div>}
 {!data?<div className="empty">{loading?'جارٍ تحميل مساحة العمل…':'البيانات غير متاحة الآن'}{!loading&&<a href="/signin-with-chatgpt?return_to=/" target="_top">تسجيل الدخول</a>}</div>:<><div className="page-heading"><div><p className="eyebrow">{page==='today'?'كل موعد في مكانه':'مواعيد / '+names[page]}</p><h1>{page==='today'?'يوم مرتب، وتجربة أجمل.':names[page]}</h1><p>{page==='today'?humanDate(date):page==='bookings'?'الحجز والتعديل ومتابعة رحلة العميلة.':page==='customers'?'بيانات التواصل وسجل الزيارات.':page==='team'?'الخدمة المناسبة، في الوقت المناسب.':page==='reports'?'قراءة التشغيل من المواعيد المسجلة فعليًا.':'إعدادات الفرع وإدارة مساحة العمل.'}</p></div>{['today','bookings'].includes(page)?<button className="primary" onClick={()=>open('booking')}><Plus size={18}/> حجز جديد</button>:page==='customers'?<button className="primary" onClick={()=>open('customer')}><Plus size={18}/> إضافة عميلة</button>:page==='team'?<button className="primary" onClick={()=>open(teamTab==='services'?'service':'staff')}><Plus size={18}/>{teamTab==='services'?'إضافة خدمة':'إضافة موظفة'}</button>:null}</div>{data.demo&&<div className="demo-banner"><Sparkles size={17}/><span>هذه بيانات توضيحية يمكنك تعديلها بحرية. ابدئي بمساحة فارغة من الإعدادات عندما تكونين جاهزة.</span></div>}<Views data={data} page={page} date={date} setDate={setDate} open={open} setPage={setPage} teamTab={teamTab} setTeamTab={setTeamTab} setConfirm={setConfirm}/></>}
 </main></SidebarInset>{data&&<Forms {...{data,modal,setModal,form,setForm,formError,setFormError,confirm,setConfirm,busy,act,open}}/>}</SidebarProvider>;
}

