"use client";
import {useState,useEffect,useRef} from 'react';
import {CalendarDays,Clock3,Users,Scissors,ChartNoAxesCombined,Plus,Settings2,RefreshCw,ShieldCheck,UsersRound,ChevronLeft,LogOut,Building2,ArrowUpLeft} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {dayNow} from '@/lib/domain.mjs';
import type {State,Access} from './types';
import {humanDate,BookingTable} from './ui';
import Views from './views';
import Forms from './forms';
import UserCenter from './user-center';
const names:Record<string,string>={today:'نظرة اليوم',bookings:'الحجوزات',customers:'العملاء',team:'الخدمات والفريق',users:'مركز المستخدمين',reports:'التقارير',settings:'الإعدادات'};
const roleNames={admin:'مسؤول المساحة',owner:'مالك صالون',customer:'عميل'};
export default function Workspace(){
 const [data,setData]=useState<State|null>(null),[access,setAccess]=useState<Access|null>(null),[rev,setRev]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState('today'),[date,setDate]=useState(dayNow()),[teamTab,setTeamTab]=useState('services');
 const [modal,setModal]=useState<{kind:string;item?:any}|null>(null),[form,setForm]=useState<any>({}),[formError,setFormError]=useState(''),[confirm,setConfirm]=useState<any>(null);
 const busyRef=useRef(false),live=useRef({data,rev,date,access});live.current={data,rev,date,access};
 const endpoint=()=>'/api/workspace'+(window.location.search||'');
 async function load(){setLoading(true);try{const r=await fetch(endpoint(),{cache:'no-store'});const j:any=await r.json();if(!r.ok){if(r.status===401||r.status===403){setData(null);setAccess(null)}throw Error(j.error)}setData(j.state);setAccess(j.access);setRev(j.revision);setError('')}catch(e:any){setError(e.message||'تعذر الاتصال')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function act(action:any){if(busyRef.current)return false;busyRef.current=true;setBusy(true);try{const r=await fetch(endpoint(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:live.current.rev,action})});const j:any=await r.json();if(!r.ok){if(r.status===409)await load();if(r.status===401||r.status===403){setModal(null);await load()}throw Error(j.error||'تعذر الحفظ')}setData(j.state);setAccess(j.access);setRev(j.revision);live.current={...live.current,data:j.state,rev:j.revision,access:j.access};setError('');toast.success('تم الحفظ');return true}catch(e:any){setFormError(e.message);toast.error(e.message);return false}finally{busyRef.current=false;setBusy(false)}}
 function open(kind:string,item?:any,defaults?:any){setFormError('');setModal({kind,item});setForm(item?{...item}:{id:crypto.randomUUID(),name:'',email:'',phone:'',notes:'',role:kind==='user'?'owner':'',status:'active',salonName:'',customerId:'',start:'09:00',end:'21:00',active:true,duration:45,buffer:10,price:0,staffId:'',serviceId:'',date:live.current.date,time:'10:00',...defaults})}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[{name:'read_salon_day',description:'Read only bookings visible to the signed-in account for a Saudi calendar date.',inputSchema:{type:'object',properties:{date:{type:'string',pattern:'^20[0-9]{2}-[0-9]{2}-[0-9]{2}$'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!/^20\d{2}-\d{2}-\d{2}$/.test(input?.date))throw Error('Invalid date');if(!live.current.data)throw Error('Workspace not loaded');return live.current.data.bookings.filter(b=>b.date===input.date).map(b=>({id:b.id,time:b.time,status:b.status,service:b.serviceName}))}},{name:'start_salon_booking',description:'Open a booking form for salon operators. Does not save.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>{if(!live.current.data||live.current.access?.role==='customer')throw Error('Not available');open('booking');return {opened:true,saved:false}}}];for(const t of tools)try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
 const isClient=access?.role==='customer';
 const navigation=[[CalendarDays,'today'],[Clock3,'bookings'],[Users,'customers'],[Scissors,'team'],[UsersRound,'users'],[ChartNoAxesCombined,'reports'],[Settings2,'settings']].filter(([,key])=>isClient?key==='bookings':key!=='users'||access?.role==='admin');
 return <SidebarProvider><Toaster position="top-center" richColors dir="rtl"/><Sidebar side="right"><SidebarHeader><div className="brand"><span>م</span><strong>مواعيد<small>إدارة الصالونات والحجوزات</small></strong></div><div className="workspace-label"><Building2 size={16}/><span>{data?.settings.name||'مساحة العمل'}</span><span className="mini-dot"/></div></SidebarHeader><SidebarContent><p className="nav-caption">{isClient?'حسابي':'مساحة الإدارة'}</p><SidebarMenu>{navigation.map(([Icon,key])=>{const I=Icon as typeof CalendarDays;return <SidebarMenuItem key={String(key)}><SidebarMenuButton isActive={isClient?key==='bookings':page===key} onClick={()=>setPage(String(key))}><I/><span>{names[String(key)]}</span>{key==='users'&&<span className="nav-count">{data?.users.length||0}</span>}</SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu><div className="sidebar-note"><ShieldCheck size={21}/><strong>وصول بحسب الدور</strong><p>بيانات العملاء للمخولين، وإدارة الصلاحيات بيد المسؤول.</p></div></SidebarContent><SidebarFooter><div className="branch"><span className="avatar color0">{access?.name?.[0]||'م'}</span><div><strong>{access?roleNames[access.role]:'حساب مواعيد'}</strong><small>المملكة العربية السعودية</small></div><a aria-label="تسجيل الخروج" href="/signout-with-chatgpt" className="icon-button"><LogOut size={16}/></a></div></SidebarFooter></Sidebar><SidebarInset>
 <header className="trust-header"><div className="header-main"><div className="header-location"><SidebarTrigger aria-label="فتح القائمة"/><span className="header-platform">مواعيد</span><ChevronLeft size={14}/><strong>{isClient?'حجوزاتي':names[page]}</strong></div><div className="header-tools"><span className="access-label"><ShieldCheck size={16}/>{access?'جلسة مسجلة':'تسجيل الدخول'}</span><button className="icon-button" aria-label="تحديث البيانات" disabled={loading||busy} onClick={()=>load()}><RefreshCw size={16} className={loading?'animate-spin':''}/></button><span className="header-divider"/><div className="header-account"><span className="avatar color0">{access?.name?.[0]||'م'}</span><div><strong>{access?roleNames[access.role]:'مرحبًا بك'}</strong><small>{access?.email||'مواعيد'}</small></div></div></div></div><div className="header-context"><span><span className="mini-dot"/>{data?.settings.name||'مساحة العمل'}<span className="context-separator">/</span>توقيت الرياض</span><span className={'environment-tag '+(data?.demo?'is-demo':'')}>{data?.demo?'وضع التجربة':'مساحة العمل'}</span></div></header>
 <main className="workspace">{error&&<div role="alert" className="error">{error}<button onClick={()=>load()}>إعادة المحاولة</button></div>}{!data||!access?<div className="empty">{loading?'جارٍ تحميل مساحة العمل…':'مساحة العمل غير متاحة لهذا الحساب'}{!loading&&<a className="text-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(typeof window==='undefined'?'/':window.location.pathname+window.location.search)} target="_top">تسجيل الدخول</a>}</div>:<>
 <div className="page-heading"><div><p className="eyebrow">{isClient?'حساب العميل':page==='users'?'الإدارة / الوصول والصلاحيات':'مساحة العمل / '+names[page]}</p><h1>{isClient?'حجوزاتي':page==='today'?'كل المواعيد. بنظرة واحدة.':names[page]}</h1><p>{isClient?'مواعيدك وحالتها في مكان واحد.':page==='today'?humanDate(date):page==='users'?'إدارة ملاك الصالونات والعملاء وصلاحية الوصول.':page==='bookings'?'تنظيم الحجوزات ومتابعة كل زيارة.':page==='customers'?'بيانات التواصل وسجل الزيارات.':page==='team'?'الخدمات وأوقات عمل الفريق.':page==='reports'?'مؤشرات التشغيل من الحجوزات المسجلة.':'إعدادات الفرع ومساحة العمل.'}</p></div>{!isClient&&(['today','bookings'].includes(page)?<button className="primary" onClick={()=>open('booking')}><Plus size={16}/> حجز جديد</button>:page==='users'&&access.role==='admin'?<button className="primary" onClick={()=>open('user')}><Plus size={16}/> إضافة مستخدم</button>:page==='customers'?<button className="primary" onClick={()=>open('customer')}><Plus size={16}/> إضافة عميل</button>:page==='team'?<button className="primary" onClick={()=>open(teamTab==='services'?'service':'staff')}><Plus size={16}/>{teamTab==='services'?'إضافة خدمة':'إضافة عضو للفريق'}</button>:null)}</div>
 {data.demo&&<div className="demo-banner"><span className="demo-badge">تجربة</span><span>البيانات التوضيحية قابلة للتعديل. يمكنك بدء مساحة فارغة من الإعدادات قبل إضافة حسابات المستخدمين.</span>{!isClient&&<button onClick={()=>setPage('settings')} aria-label="إعداد مساحة العمل"><ArrowUpLeft size={16}/></button>}</div>}
 {isClient?<section className="panel"><BookingTable rows={data.bookings.slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))} data={data} open={open}/></section>:page==='users'&&access.role==='admin'?<UserCenter {...{data,access,open,setConfirm,busy}}/>:<Views data={data} page={page==='users'?'today':page} date={date} setDate={setDate} open={open} setPage={setPage} teamTab={teamTab} setTeamTab={setTeamTab} setConfirm={setConfirm}/>}
 <footer className="workspace-footer"><span>مواعيد <span>·</span> إدارة أوضح لكل يوم</span><span>المساعدة في البيانات؟ تواصل مع مسؤول المساحة</span></footer></>}</main></SidebarInset>{data&&<Forms {...{data,modal,setModal,form,setForm,formError,setFormError,confirm,setConfirm,busy,act,open,readOnly:isClient}}/>}</SidebarProvider>;
}
